paranext/paranext-extension-template

.gitignore
.vscode/launch.json
README.md
lib/extension-template-html.web-view.ejs
lib/extension-template.web-view.tsx
lib/main.ts
lib/vite-env.d.ts
package-lock.json
package.json
public/manifest.json
public/package.json
tsconfig.json
tsconfig.node.json
vite.config.ts

Resolves #1 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/paranext/paranext-extension-template/6)

Added Vite/TypeScript/React and pulling papi.d.ts

---

lib/extension-template-html.web-view.ejs
package.json
public/manifest.json
public/package.json
vite.config.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/paranext/paranext-extension-template/7)

Changed extensions back to commonjs because paranext does not support es modules in production

---

lib/extension-template-html.web-view.ejs
lib/extension-template.web-view.scss
lib/extension-template.web-view.tsx
lib/main.ts
package-lock.json
package.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/paranext/paranext-extension-template/8)

Added scss style example

---

vite/vite-web-view.config.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/paranext/paranext-extension-template/12)

Replace NODE_ENV on WebViews in Vite

---

package-lock.json
package.json

- will resolve 1 dependabot PR
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/paranext/paranext-extension-template/16)

Fix vite security vulnerability

---

lib/extension-template-html.web-view.ejs
lib/extension-template.web-view.tsx
lib/main.ts
public/assets/heresy-warning.txt
public/paranext-extension-template.d.ts
tsconfig.json

And other updates to match existing extension code to show other features and such
Relates to https://github.com/paranext/paranext-core/issues/109
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/paranext/paranext-extension-template/13)

Updated data provider to data type api

---

lib/extension-template.web-view.tsx
lib/main.ts
vite/vite.util.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/paranext/paranext-extension-template/20)

Update for split `papi.d.ts`

---

package-lock.json
package.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/paranext/paranext-extension-template/21)

Upgrade TypeScript

---

lib/main.ts
package-lock.json
public/paranext-extension-template.d.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/paranext/paranext-extension-template/22)

Replace fetch to bible-api.com with the USFM data provider

---

.editorconfig
.vscode/settings.json

- also VS Code rulers and EOF
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/paranext/paranext-extension-template/23)

Set `.editorconfig`

---

.vscode/settings.json
lib/main.ts
package-lock.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/paranext/paranext-extension-template/25)

Fix problems seen when using the latest core branch

---

.vscode/launch.json
src/main.ts

- Change how subscriptions are returned
- Update VS Code debug label
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/paranext/paranext-extension-template/33)

Apply updates based on changes to core

---

.vscode/launch.json

See instructions for [Debugging Your Extension in the Production Application](https://github.com/paranext/paranext-extension-template/wiki/Debugging-Your-Extension-in-the-Production-Application) extension Wiki page.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/paranext/paranext-extension-template/34)

Debug production

---

README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/paranext/paranext-extension-template/36)

Extend readme with update section

---

src/types/paranext-extension-template.d.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/paranext/paranext-extension-template/37)

Rename papi-commands to papi-shared-types

---

webpack/webpack.config.base.ts

This reverts commit 5eeb76375c456284b936cd50593be48b635c7128.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/paranext/paranext-extension-template/49)

Revert "Update webpack.config.base.ts"

---

src/webpack-env.d.ts
webpack/webpack.config.base.ts

Corresponds to https://github.com/paranext/paranext-core/pull/610
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/paranext/paranext-extension-template/50)

Allow data urls

---

src/main.ts
webpack/webpack.config.base.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/paranext/paranext-extension-template/51)

Update papi imports

---

.eslintrc.js
package-lock.json
package.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/paranext/paranext-extension-template/53)

Add ESLint rule for flagging use of "null"

---

.eslintrc.js
src/main.ts
webpack/webpack.config.base.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/paranext/paranext-extension-template/54)

650 refactor imports (extension template)

---

.eslintignore
.eslintrc.js
.gitignore
.prettierignore
.prettierrc.js
.stylelintignore
.stylelintrc.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/paranext/paranext-extension-template/56)

Added 'shared with' statements to various style files and brought them in sync

---

.eslintrc.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/paranext/paranext-extension-template/57)

Removed no-non-null-assertion as it is covered by no-type-assertion

---

package-lock.json
package.json
webpack/webpack.config.base.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/paranext/paranext-extension-template/58)

Fixed emotion package duplication

---

contributions/localizedStrings.json
manifest.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/paranext/paranext-extension-template/67)

Added localized string contribution doc

---

manifest.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/paranext/paranext-extension-template/68)

Fixed typo in contributions path

---

assets/descriptions/description-en.md
assets/displayData.json

I think in these places it should say Platform.Bible.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/paranext/paranext-extension-template/75)

Changed a couple places in files where we descriptions that refer to Paranext

---

webpack/webpack.config.base.ts
webpack/webpack.config.main.ts
webpack/webpack.util.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/paranext/paranext-extension-template/82)

Moved LIBRARY_TYPE to match multi template

---

.stylelintrc.js
package-lock.json
package.json

- let prettier format CSS & SCSS
- also `npm audit fix`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/paranext/paranext-extension-template/86)

add missing format checks

---

LICENSE

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/paranext/paranext-extension-template/89)

#1587: Changed (c) to © in LICENSE file (for consistency)

---

manifest.json

Goes with https://github.com/paranext/paranext-core/pull/1425
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/paranext/paranext-extension-template/90)

Added publisher to manifest

---

webpack/webpack.config.base.ts
webpack/webpack.config.main.ts
webpack/webpack.config.web-view.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/paranext/paranext-extension-template/93)

Changed main file target so it understands built-in modules except crypto are not available

---

README.md
manifest.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/paranext/paranext-extension-template/94)

Adjusted extension name guidance - lowerCamelCase and kebab-case

---

README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/paranext/paranext-extension-template/96)

PT-2390: Minor wording improvements to README

---

webpack/webpack.config.base.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/paranext/paranext-extension-template/97)

Remove MUI

---

.github/assets/release-body.md
.github/workflows/publish.yml
README.md
lib/bump-versions.ts
lib/git.util.ts
package.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/paranext/paranext-extension-template/99)

Set up auto-release workflow

---

README.md

Foiled again...
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/paranext/paranext-extension-template/100)

Fixed out-of-order readme section

---

lib/bump-versions.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/paranext/paranext-extension-template/101)

Added consistent return in bump-versions

---

.github/workflows/publish.yml
README.md
lib/bump-versions.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/paranext/paranext-extension-template/102)

Small fixes to auto-release process

---

.gitattributes
.github/workflows/lint.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/paranext/paranext-extension-template/106)

Add github action for CI with lint and format check

---

tailwind.config.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/paranext/paranext-extension-template/108)

Update Tailwind prose colors

---

src/main.ts

Part of reducing unnecessary logs in https://paratextstudio.atlassian.net/browse/PT-2579
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/paranext/paranext-extension-template/110)

Swapped built-in logs to debug since we already have logs that cover this in core; they are just sample actions

---

webpack.config.ts
webpack/web-view-resolve-webpack-plugin.ts
webpack/webpack.config.base.ts
webpack/webpack.config.main.ts
webpack/webpack.config.web-view.ts
webpack/webpack.util.ts

Replace various "web view", "webView", and "web-view" occurrences in the comments.
Also capitalize a few sentences.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/paranext/paranext-extension-template/111)

Use standard 'WebView' in comments

---

README.md
package-lock.json
src/types/paranext-extension-template.d.ts

Clarified template use
Minor formatting/capitalization/wording tweaks
Added some content to bring README.md into sync with the one in paranext-multi-extension-template
Added some HTML comments to make it easier to keep the two versions appropriately in sync in the future
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/paranext/paranext-extension-template/114)

PT-2390: README improvements

---

README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/paranext/paranext-extension-template/117)

Fixed typo: proceeding

---

package-lock.json
package.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/paranext/paranext-extension-template/119)

Bump versions of node and swc to align with core

---

README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/paranext/paranext-extension-template/122)

Reworked readme to link to correct explanation of swc/core problems, updated readme with bump-versions.yml
